# -------------------------
# Infrastructure parameters
# -------------------------

project_root: /Users/owenjow/bracketfill

data:
  root: /Users/owenjow/bracketfill/data
  csv_stats:
    path: summer_2017.csv
    type: h2h
    limits:
      min_col: 2
      max_col: -6
  tag:
    fuzz_threshold: 75
  collect:
    smash_gg:
      api_base: https://api.smash.gg
      event:
        - melee-singles
        - super-smash-bros-melee
      tournament_url_file: urls_past_101+_06_08_17.txt
      out: sets_past_101+_06_08_17.pickle

train:
  model: LogisticRegression
  restore_itr: X
  outfolder: out
  batch_size: 64
  max_steps: 30000
  checkpoint_freq: 1000
  report_freq: 1000
  lr: 0.1
  sets_source:
    - summer_2017.csv
  players_source:
    - profiles.csv

eval:
  restore_itr: 3000

# ----------------
# Model parameters
# ----------------

inputs:
  main:
    dtype: float32
    shape: [2]
    transform: [30, 1]
  floaty:
    dtype: float32
    shape: [2]
  ranking:
    dtype: float32
    shape: [2]
    transform: X

outputs:
  winner:
    dtype: float32
    shape: []
